### ISSUE TITLE
Clarify locks section

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#12]
Need to clarify the lock requirements, especially around lock mismatches and the headers that should be returned by the host.

**Comment by chrisbro-MSFT** [comment]
Document what the host should do if we make a Lock call to a file that is already locked and the correct LockId is provided.

**Comment by chrisbro-MSFT** [comment]
Should the host send the current lock string back with X-Wopi-Lock or X-Wopi-OldLock?  Docs say one thing, SPO says another.

**Comment by chrisbro-MSFT** [comment]
There are X-WOPI-LockFailureReason and X-WOPI-LockedByOtherInteface response headers that SPO can send.  Need to determine if they matter and if so add them to our docs.

**Comment by TurtleShip** [comment]
It would also be nice if you could add the below information
1. Which lock operations require X-WOPI-OldLock / X-WOPI-Lock headers.

2. How Office Online is using RefreshLock
From what @chrisbro-MSFT described,
"WOPI doesn’t have a GetLock operation right now, so the apps tend to do a RefreshLock with a random value so that they can learn the current lock string, and because of the async order in which Word spins up its pieces that’s likely to happen at least once per session."

**Comment by tylerbutler** [comment]
Pull request #61 is in review.
