### ISSUE TITLE
CheckFileInfo + X-WOPI-Override

### ISSUE THREAD

**Issue by mnpenner** [Microsoft/Office-Online-Test-Tools-and-Documentation#256]
All of these actions use the same URL:

- CheckFileInfo
- PutRelativeFile
- Lock
- Unlock
- RefreshLock
- UnlockAndRelock
- DeleteFile
- RenameFile

All of them except `CheckFileInfo` are requested with the `X-WOPI-Override` header -- I assume that's how we're supposed to differentiate them?

I was about to ask how we were supposed to identify a `CheckFileInfo` request but I've just now noticed that `CheckFileInfo` is a `GET` and all the others are `POST`.

I think something should be added to the docs to clarify that `GET /wopi/files/(file_id)` == `CheckFileInfo`, and `POST /wopi/files/(file_id)` means you need to check `X-WOPI-Override`.

**Comment by tylerbutler** [comment]
This hasn't been a point of confusion so far, and I'm not sure where or how we'd further clarify it. Each operation indicates the header values and HTTP method used, and the approach of using a header to indicate which particular operation is being executed is relatively common across REST APIs. The [endpoints section](https://wopi.readthedocs.io/projects/wopirest/en/latest/endpoints.html) describes each endpoint in a little more detail along with the operations that are exposed on it. Plus [the WOPI validator](https://wopi.readthedocs.io/en/latest/build_test_ship/validator.html) makes it pretty obvious if you end up getting this wrong.

I'm inclined to close this for now, and see if it comes up again, since it hasn't been an issue thus far.

**Comment by mnpenner** [comment]
OK, no problem. Might just be me then; had it in my mind that they would all use `X-WOPI-Override`.
