### ISSUE TITLE
In PutUserInfo operation is the "id" parameter the user Id or file Id?

### ISSUE THREAD

**Issue by deaps** [Microsoft/Office-Online-Test-Tools-and-Documentation#277]
In the top of PutUserInfo documentation page the URL have the placeholder for the parameter "id" (`post:: /wopi*/files/(id)`) and in the list of parameters in the middle of the page (`include:: /fragments/common_params.rst`) it is displayed as "file_id", but since this is PutUserInfo why we need the file_id? Is this a typo?

Also if this is a user related operation shouldn't it be in a users endpoint instead of files endpoint?

**Comment by tylerbutler** [comment]
It's a bit odd, yes, but the PutUserInfo operation is called in the context of a file. Hence, it's on the files endpoint. There is currently no users endpoint in WOPI.

I am going to go ahead and close this issue, since I think I've addressed your questions. Please re-open it or add new issues if you have further questions or if this did not adequately address your original questions.
