### ISSUE TITLE
FAQ: What is the minimal WOPI host required to implement?

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#30]
Answer: CheckFileInfo and GetFile

**Comment by MarcinJuraszek** [comment]
I would make it clear:

 - **View**: `CheckFile` and `GetFile`
 - **Edit**: `CheckFile`, `GetFile` `PutFile`, `Lock`, `Unlock`, `UnlockAndRelock`, `RefreshLock`.

Also, `GetFile` is not really necessary, because you can use `DirectReadURL` on `CheckFile` response to make Office Online boot without doing a `GetFile` request. 

btw. `DirectReadURL` is not documented.

**Comment by tylerbutler** [comment]
> Also, GetFile is not really necessary, because you can use FileURL on CheckFile response to make Office Online boot without doing a GetFile request.

Not to spec - GetFile is required per spec, and it's required since we aren't 100% sure we use FileUrl in all possible cases.
