### ISSUE TITLE
Is it possible to hide the breadcrumb?

### ISSUE THREAD

**Issue by whozDougie** [Microsoft/Office-Online-Test-Tools-and-Documentation#308]
Hi, 

Was wondering if it is possible to hide the breadcrumb all together? 

Or alternatively, allow the display of the common options available in "view" mode within the "embedview" mode.
![image](https://cloud.githubusercontent.com/assets/11555622/24280122/6398a298-10a2-11e7-81de-ee866058a236.png)

At the moment, when I run our wopi integration through the validator's  FullCheckFileInfoSchema test, I get it complaining about this:

**Uri Expected: BreadcrumbBrandUrl, BreadcrumbFolderUrl**

The response from our WOPI Host is:
```
{
  "BaseFileName": "validate.wopitest",
  "OwnerId": "username@email.com",
  "Size": 1,
  "Version": "0",
  "BreadcrumbBrandName": "Brand Name",
  "BreadcrumbBrandUrl": "",
  "BreadcrumbFolderName": "",
  "BreadcrumbFolderUrl": "",
  "BreadcrumbDocName": "validate.wopitest",
  "UserCanWrite": false,
  "ReadOnly": true,
  "SupportsLocks": false,
  "SupportsUpdate": false,
  "UserCanNotWriteRelative": true,
  "UserFriendlyName": "username@email.com",
  "UserId": "username@email.com"
}
```

Any help on this would be greatly appreciated.

Cheers,
Doug

**Comment by tylerbutler** [comment]
Just omit the properties altogether. All optional properties in CheckFileInfo can (and should) be omitted, because defaults are always explicitly defined as part of the spec. The reason the validator is complaining is because the Breadcrumb URL properties, if specified, must be absolute URLs. Technically speaking, in Office Online your implementation would be equivalent to omitting them. But still... just omit what you're not using.

**Comment by whozDougie** [comment]
Many thanks Tyler
