### ISSUE TITLE
Office Online App stops responding via PREVIEW/EDIT, when it is running from AWS EC2

### ISSUE THREAD

**Issue by lostbeaver** [Microsoft/Office-Online-Test-Tools-and-Documentation#350]
We've faced problem with running our integration tests in AWS EC2: time to time when we tried to open document for edit/preview Office Online App (Excel, Powerpoint, Word, no matter what application) show error notification 'Not responding'.

We do not have such problem, when we run tests in different place in California.

So, it will be pretty nice if you'll help us with it and take a look in your logs, what can be the reason of this error. Here is Session ID from one of these error notifications:
a9cebe5c-2ad9-413b-877d-10c10c2db561

**Comment by tylerbutler** [comment]
@lostbeaver Unfortunately I don't see any record of that session in any of our logs. I suggest moving this conversation to the CSPP Yammer group, which is a better place for support of particular integration issues as opposed to documentation issues.

Regardless, we'll need a Fiddler trace of the failures in order to investigate more deeply.
