### ISSUE TITLE
WOPI doesn't request Office 365 license

### ISSUE THREAD

**Issue by armikhailov** [microsoft/Office-Online-Test-Tools-and-Documentation#464]
When a business user opens a document in `edit` mode, there is no license check. `LicenseCheckForEditIsEnabled` property is set to `true` for business users. Also `IsLicensedUser=1` parameter is set to `WOPISrc`. All according to this [page](https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/scenarios/business). But this step doesn't show up:

![IMG_001](https://user-images.githubusercontent.com/119608329/205086867-cd84bb71-9307-43d2-b3cd-0090d6c19467.png)

**Comment by cesco69** [comment]
Same for me! +1

**Comment by v-stefansi** [comment]
Hi @armikhailov we did make a change to the business user flow several months ago and what you outline above is now the expected behavior.  While we made an announcement in the CSPP Yammer channel at the time, the documentation is still in the process of being updated.  Let me know if you don't have access to the CSPP Yammer channel and I'll get that taken care of for you.
