### ISSUE TITLE
X-WOPI-RelativeTarget, X-WOPI-SuggestedTarget, and X-WOPI-RequestedName must be UTF-7 encoded strings

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/Office-Online-Test-Tools-and-Documentation#54]

**Comment by tylerbutler** [comment]
@chrisbro-MSFT, can you confirm that these strings should all be UTF-7 encoded? Are there others that I should call out as well?

**Comment by chrisbro-MSFT** [comment]
The host can 400 or 409 a PutRelativeFile response and send a X-WOPI-ValidRelativeTarget header that indicates a valid name that can be used instead of the name we suggested.  For example, if the file we suggest already exists and we have passed the "do not overwrite" header.  The value of the X-WOPI-ValidRelativeTarget header must be UTF7 encoded.

**Comment by chrisbro-MSFT** [comment]
Actually, they shouldn't 400 with a ValidRelativeTarget.  They should 409.  If we want to PutRelativeFile, we offer a filename, and we can't save to that filename (it already exists, the filename is invalid, etc) then the host MAY 409 with an X-WOPI-ValidTarget header in the response (utf7 encoded).  If so, we will automatically retry the operation with the proposed name without showing an error to the user.  Don't infinite loop please.
